version: '3.1'

services:
  nginx:
    image: nginx
    # 컨테이너별 로그 저장 정책을 결정합니다.
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "300m"
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
networks:
  corn_net:
    driver: bridge