version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: root
    volumes:
      - /var/lib/docker/volumes/prometheus/_data/:/etc/prometheus/
      - /var/lib/docker/volumes/prometheus/_data/data/:/prometheus/
    ports:
      - 9090:9090
    networks:
      - monitor
    restart: always
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    user: root
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=test1234
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - /var/lib/docker/volumes/grafana/_data/:/var/lib/grafana/
      - /var/lib/docker/volumes/grafana/_data/provisioning:/etc/grafana/provisioning/
    ports:
      - 3000:3000
    depends_on:
      - prometheus
    networks:
      - monitor
    restart: always
networks:
    monitor:
      driver: bridge